"""Tests for issue #580: orphaned task_ids must be retired so lane fallback

can't ping-pong forever between a dead task_id (left behind by removed code)
and the current lane's real work.
"""
from nanobot.runtime.coordinator import (
    _BACKLOG_PROGRESSION_IDS,
    COMPLETED_TASK_STATUSES,
    CORE_TASK_IDS,
    KNOWN_TASK_IDS,
    MATERIALIZE_SYNTHESIZED_IMPROVEMENT_ID,
    SYNTHESIZE_NEXT_IMPROVEMENT_CANDIDATE_ID,
    TASK_ACTION_CLASS_BY_ID,
    _derive_feedback_decision,
    _retire_orphaned_task_ids,
    _task_is_selectable,
)


def test_retire_orphaned_task_ids_retires_unknown_pending_task():
    orphan = {"task_id": "exploit-successful-improvement-path", "status": "pending"}
    task_records = [orphan]

    retired_count = _retire_orphaned_task_ids(task_records)

    assert retired_count == 1
    assert orphan["status"] in COMPLETED_TASK_STATUSES
    assert orphan["terminal_reason"] == "orphaned_unrecognized_task_id"
    assert _task_is_selectable(orphan) is False


def test_retire_orphaned_task_ids_leaves_known_and_already_completed_tasks_untouched():
    core_pending = {"task_id": "refresh-approval-gate", "status": "pending"}
    backlog_pending = {"task_id": "subagent-verify-materialized-improvement", "status": "pending"}
    already_done = {"task_id": "materialize-synthesized-improvement", "status": "done"}
    # An orphan that is already terminal must not be re-touched (idempotent / no clobbering).
    orphan_already_blocked = {
        "task_id": "some-removed-task",
        "status": "blocked",
        "terminal_reason": "some_other_reason",
    }
    task_records = [core_pending, backlog_pending, already_done, orphan_already_blocked]

    retired_count = _retire_orphaned_task_ids(task_records)

    assert retired_count == 0
    assert core_pending["status"] == "pending"
    assert backlog_pending["status"] == "pending"
    assert already_done["status"] == "done"
    assert orphan_already_blocked["status"] == "blocked"
    assert orphan_already_blocked["terminal_reason"] == "some_other_reason"


def test_retire_orphaned_task_ids_regression_matches_live_host_snapshot():
    """Mirrors the live 9-task snapshot from state/goals/current.json that

    motivated issue #580: 4 done bookkeeping tasks, an active verify task,
    a pending orphan (exploit-successful-improvement-path, generated by code
    removed on main between c4aea9c and e345ca1), and 3 pending core tasks.
    """
    tasks = [
        {"task_id": "materialize-synthesized-improvement", "status": "done"},
        {"task_id": "synthesize-next-improvement-candidate", "status": "done"},
        {"task_id": "inspect-pass-streak", "status": "done"},
        {"task_id": "materialize-pass-streak-improvement", "status": "done"},
        {"task_id": "subagent-verify-materialized-improvement", "status": "active"},
        {"task_id": "exploit-successful-improvement-path", "status": "pending"},
        {"task_id": "refresh-approval-gate", "status": "pending"},
        {"task_id": "run-bounded-turn", "status": "pending"},
        {"task_id": "record-reward", "status": "pending"},
    ]
    by_id = {t["task_id"]: t for t in tasks}

    retired_count = _retire_orphaned_task_ids(tasks)

    assert retired_count == 1
    orphan = by_id["exploit-successful-improvement-path"]
    assert _task_is_selectable(orphan) is False
    assert orphan["terminal_reason"] == "orphaned_unrecognized_task_id"

    verify_task = by_id["subagent-verify-materialized-improvement"]
    assert _task_is_selectable(verify_task) is True

    # Core pending tasks and the already-done bookkeeping tasks are untouched.
    for task_id in ("refresh-approval-gate", "run-bounded-turn", "record-reward"):
        assert by_id[task_id]["status"] == "pending"
    for task_id in (
        "materialize-synthesized-improvement",
        "synthesize-next-improvement-candidate",
        "inspect-pass-streak",
        "materialize-pass-streak-improvement",
    ):
        assert by_id[task_id]["status"] == "done"


def test_derive_feedback_decision_repairs_orphan_from_persisted_goal_state(tmp_path):
    """End-to-end: the retirement pass runs as part of the normal per-cycle

    feedback-decision path, operating on the same task list shape that is
    persisted to state/goals/current.json.
    """
    goals_dir = tmp_path / "goals"
    goals_dir.mkdir()
    (goals_dir / "history").mkdir()

    tasks = [
        {"task_id": "materialize-synthesized-improvement", "status": "done"},
        {"task_id": "synthesize-next-improvement-candidate", "status": "done"},
        {"task_id": "inspect-pass-streak", "status": "done"},
        {"task_id": "materialize-pass-streak-improvement", "status": "done"},
        {"task_id": "subagent-verify-materialized-improvement", "status": "active"},
        {"task_id": "exploit-successful-improvement-path", "status": "pending"},
        {"task_id": "refresh-approval-gate", "status": "pending"},
        {"task_id": "run-bounded-turn", "status": "pending"},
        {"task_id": "record-reward", "status": "pending"},
    ]
    task_plan = {
        "current_task_id": "subagent-verify-materialized-improvement",
        "tasks": tasks,
    }

    _derive_feedback_decision(task_plan, goals_dir)

    orphan = next(t for t in tasks if t["task_id"] == "exploit-successful-improvement-path")
    assert _task_is_selectable(orphan) is False
    assert orphan["terminal_reason"] == "orphaned_unrecognized_task_id"


def test_known_task_ids_is_a_superset_of_the_core_constants():
    """Guard test: KNOWN_TASK_IDS must never drift below the existing task-id

    constants — if a new constant/id is added to the code without updating
    KNOWN_TASK_IDS, this test fails loudly instead of the orphan-retirement
    logic silently starting to cancel live, in-use tasks.
    """
    assert (CORE_TASK_IDS | _BACKLOG_PROGRESSION_IDS) <= KNOWN_TASK_IDS
    for task_id in TASK_ACTION_CLASS_BY_ID:
        assert task_id in KNOWN_TASK_IDS
    assert SYNTHESIZE_NEXT_IMPROVEMENT_CANDIDATE_ID in KNOWN_TASK_IDS
    assert MATERIALIZE_SYNTHESIZED_IMPROVEMENT_ID in KNOWN_TASK_IDS
