"""#1857: ``skills/index.md`` -- machine-generated, never hand-maintained.

Reuses ``SkillsLoader.build_skills_summary(compact=True)``'s exact
one-line-per-skill rendering (#1732) rather than a second description-
extraction path -- see ``tests/test_skills_catalogue_compact.py`` for that
format's own coverage.
"""
from __future__ import annotations

from pathlib import Path

from nanobot.runtime import skills_index


def _skill(root: Path, name: str, description: str = "test skill") -> None:
    path = root / name / "SKILL.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"---\nname: {name}\ndescription: {description}\n---\n\n# {name}\n", encoding="utf-8")


def test_render_lists_workspace_skills_one_line_each(tmp_path: Path):
    _skill(tmp_path / "skills", "alpha", "does alpha things")
    _skill(tmp_path / "skills", "beta", "does beta things")

    content = skills_index.render_skills_index(tmp_path)

    assert "- alpha: does alpha things" in content
    assert "- beta: does beta things" in content


def test_render_excludes_loop_irrelevant_builtins(tmp_path: Path):
    """The generated index must agree with what the executor's own prompt
    excludes -- a skill the loop cannot use should not be advertised to it.
    Exercised against the real builtin skills directory (nanobot/skills/),
    which carries every name in LOOP_EXCLUDED_SKILLS plus at least one
    survivor (skill-creator) -- no fixture needed for this property."""
    content = skills_index.render_skills_index(tmp_path)
    for name in skills_index.LOOP_EXCLUDED_SKILLS:
        assert f"- {name}:" not in content
    assert "- skill-creator:" in content


def test_render_with_no_skills_says_so_rather_than_empty(tmp_path: Path, monkeypatch):
    """The real builtin skills directory always carries at least one
    survivor (skill-creator), so an empty catalogue is a real-but-rare
    state (a broken/missing builtins install) rather than one this
    workspace-only fixture can produce -- stub the summary directly."""
    from nanobot.agent.skills import SkillsLoader

    monkeypatch.setattr(SkillsLoader, "build_skills_summary", lambda self, **kwargs: "")
    content = skills_index.render_skills_index(tmp_path)
    assert "(no skills yet)" in content


def test_render_header_warns_against_hand_editing(tmp_path: Path):
    content = skills_index.render_skills_index(tmp_path)
    assert "Generated by the harness" in content
    assert "never hand-edit" in content


def test_write_creates_the_file_and_reports_changed(tmp_path: Path):
    _skill(tmp_path / "skills", "alpha", "does alpha things")
    changed = skills_index.write_skills_index_if_changed(tmp_path)
    assert changed is True
    target = tmp_path / skills_index.INDEX_RELPATH
    assert target.is_file()
    assert "- alpha: does alpha things" in target.read_text(encoding="utf-8")


def test_write_is_idempotent_when_nothing_changed(tmp_path: Path):
    _skill(tmp_path / "skills", "alpha", "does alpha things")
    assert skills_index.write_skills_index_if_changed(tmp_path) is True
    assert skills_index.write_skills_index_if_changed(tmp_path) is False


def test_write_reports_changed_when_a_skill_is_added(tmp_path: Path):
    _skill(tmp_path / "skills", "alpha", "does alpha things")
    skills_index.write_skills_index_if_changed(tmp_path)
    _skill(tmp_path / "skills", "beta", "does beta things")
    assert skills_index.write_skills_index_if_changed(tmp_path) is True
    target = tmp_path / skills_index.INDEX_RELPATH
    assert "- beta: does beta things" in target.read_text(encoding="utf-8")


def test_write_fails_open_on_unwritable_target(tmp_path: Path):
    blocker = tmp_path / "skills"
    blocker.write_text("not a directory", encoding="utf-8")
    changed = skills_index.write_skills_index_if_changed(tmp_path)
    assert changed is False
