#!/usr/bin/env bash
# =============================================================================
# apply_preset.sh — activate a named operator preset (#906)
#
# Usage (on the eeepc host, as root):
#   sudo bash apply_preset.sh <name>
#
# What it does:
#   1. Validates /etc/eeepc-agent/presets/<name>.env exists — exits 1 with a
#      clear message and makes NO changes if it doesn't.
#   2. Points the /etc/eeepc-agent/preset.env symlink at that file. The
#      bridge service unit loads this file (optionally, `-` prefix) BEFORE
#      the per-instance env file, so instance-file values still win per
#      variable — see host/eeepc/systemd/eeepc-self-evolving-subagent-bridge.service.
#   3. Reads SELFEVO_CYCLE_PAUSE out of the preset and translates it into a
#      systemd timer drop-in: OnUnitActiveSec=<blank> (clears the stock 15m
#      value) + OnUnitInactiveSec=<pause>. OnUnitInactiveSec fires N after
#      the PREVIOUS run ENDS rather than N after it STARTED, which also
#      sidesteps the OnUnitActiveSec + NTP clock-adjustment timer-stagnation
#      failure mode recorded in lessons/errors.yaml (ERR-2026-2026-06-14-003:
#      OnUnitActiveSec lost its activation marker under NTP drift on this
#      same Eee PC hardware). If SELFEVO_CYCLE_PAUSE is empty/unset, the
#      drop-in is removed instead, restoring the unit's own stock 15m timer.
#   4. `systemctl daemon-reload` and prints the resulting effective profile.
#
# stdlib/bash only, fail-open by construction: an invalid preset name changes
# nothing (validated before any mutation); a missing/blank SELFEVO_CYCLE_PAUSE
# just means "no drop-in", never an error.
# =============================================================================

set -euo pipefail

PRESETS_DIR=/etc/eeepc-agent/presets
PRESET_SYMLINK=/etc/eeepc-agent/preset.env
TIMER_DROPIN_DIR=/etc/systemd/system/eeepc-self-evolving-subagent-bridge.timer.d
TIMER_DROPIN_FILE="$TIMER_DROPIN_DIR/preset.conf"

log()  { echo "[apply_preset] $*"; }
err()  { echo "[apply_preset] ERROR: $*" >&2; }

if [[ $# -ne 1 || -z "${1:-}" ]]; then
  err "usage: apply_preset.sh <name>"
  exit 1
fi

NAME="$1"
PRESET_FILE="$PRESETS_DIR/$NAME.env"

# --- 1. validate --------------------------------------------------------
if [[ ! -f "$PRESET_FILE" ]]; then
  err "preset '$NAME' not found at $PRESET_FILE — no changes made."
  err "available presets:"
  for f in "$PRESETS_DIR"/*.env; do
    [[ -f "$f" ]] || continue
    err "  - $(basename "${f%.env}")"
  done
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  err "must run as root (sudo bash $0 $NAME)"
  exit 1
fi

# --- 2. activate the symlink ---------------------------------------------
log "activating preset '$NAME' -> $PRESET_FILE"
ln -sfn "$PRESET_FILE" "$PRESET_SYMLINK"

# --- 3. read the preset (subshell — never pollute this script's own env) --
# Values default to empty so an unset var in the preset file reads as "".
SELFEVO_PRESET=""
SELFEVO_PROPOSER_MODEL=""
SUBAGENT_BRIDGE_MODEL=""
SELFEVO_CYCLE_PAUSE=""
SELFEVO_MAX_TOOL_ITERATIONS=""
# shellcheck disable=SC1090
set -a
source "$PRESET_FILE"
set +a

# --- 4. timer drop-in from SELFEVO_CYCLE_PAUSE ---------------------------
if [[ -n "$SELFEVO_CYCLE_PAUSE" ]]; then
  log "materializing timer drop-in: OnUnitInactiveSec=$SELFEVO_CYCLE_PAUSE"
  mkdir -p "$TIMER_DROPIN_DIR"
  cat > "$TIMER_DROPIN_FILE" <<EOF
# Generated by apply_preset.sh for preset '$NAME' — do not hand-edit, it will
# be overwritten (or removed) on the next apply_preset.sh run.
#
# OnUnitActiveSec is cleared (blank) because systemd only lets ONE of
# OnUnitActiveSec/OnUnitInactiveSec drive a given timer meaningfully once a
# drop-in adds the other — and OnUnitActiveSec is additionally documented as
# unreliable on this hardware: lessons/errors.yaml ERR-2026-2026-06-14-003
# records the stock 15m OnUnitActiveSec timer stagnating ("Trigger: n/a")
# after an NTP clock adjustment. OnUnitInactiveSec (N after the previous run
# ENDS) avoids that failure mode and self-adapts to cycle length.
[Timer]
OnUnitActiveSec=
OnUnitInactiveSec=$SELFEVO_CYCLE_PAUSE
EOF
else
  if [[ -f "$TIMER_DROPIN_FILE" ]]; then
    log "SELFEVO_CYCLE_PAUSE unset — removing timer drop-in (stock 15m timer)"
    rm -f "$TIMER_DROPIN_FILE"
  else
    log "SELFEVO_CYCLE_PAUSE unset — no timer drop-in to remove (stock 15m timer)"
  fi
fi

# --- 5. reload + report ----------------------------------------------------
systemctl daemon-reload

log "=== effective profile ==="
log "preset:            ${SELFEVO_PRESET:-$NAME}"
log "proposer model:    ${SELFEVO_PROPOSER_MODEL:-<unset — falls back to bridge/default>}"
log "executor model:    ${SUBAGENT_BRIDGE_MODEL:-<unset — falls back to default>}"
log "cycle pause:       ${SELFEVO_CYCLE_PAUSE:-<unset — stock 15m OnUnitActiveSec timer>}"
log "max tool iters:    ${SELFEVO_MAX_TOOL_ITERATIONS:-<unset — falls back to config default>}"
log "note: any variable also set in the instance env file"
log "      (/etc/eeepc-agent/instances/self-evolving-subagent-bridge.env) overrides this preset."
