"""Hypotheses -> priorities reader (#751).

Gives the LLM proposer (``nanobot.runtime.llm_proposer``) a bounded,
fail-open read of the strategist's ``state_dir/hypotheses/durable.json``
(written by :func:`append_hypotheses` from the daily strategist run) as
candidate ``serves: hypothesis <id>`` targets, plus a small lifecycle
(active -> answered/stale, orphaned when absent — #1346) so the context
doesn't re-offer resolved or abandoned candidates forever.

Sources — ``durable.json`` only, since #1356. History of the others:
``research/hypotheses.json`` lost its writer with the planner (#916/#923,
removed as a source in #1219). ``hypotheses/backlog.json`` was #751's primary
source: first written by the planner's ``cycle_persist``, then (#913) by the
bridge's ``backlog_snapshot.write_backlog_snapshot`` at the end of every run
from the request queue minus handled markers. One request per cycle,
proposed in one bridge run and executed in the next, meant the file
alternated between one entry (the request the loop had just written for
itself) and none — never a backlog — and every transient entry minted a
``hypothesis-llm-proposer-cycle-*`` lifecycle row that #1346 then found
orphaned (82 of 100). Writer and reader retired together in #1356; the live
file is left inert on the host, read by nothing here.

Design note — why lifecycle state is NOT stored inside the source file: the
sources are regenerated by their own writers, so any status key added to an
entry would be wiped by the next write. This module owns a small sidecar,
``state_dir/hypotheses/lifecycle.json``, keyed by a stable candidate key
(the entry's ``hypothesis_id`` when present, else a slug of the title) that
it reads/writes exclusively — additive-only, never dropping unknown fields.

Everything here is fail-open: a missing/corrupt file, or any unexpected
shape, degrades to "no candidates" / "no lifecycle change" rather than
raising. Nothing here ever touches ``durable.json`` itself — it remains
owned by :func:`append_hypotheses`.

#878 (closing the hypothesis -> experiment -> verdict loop): ``reconcile``
now also computes a harness-MEASURED verdict (:mod:`hypothesis_verdict`) the
same pass it first marks a candidate ``answered``, persisting ``verdict``/
``verdict_evidence``/``verdict_at`` onto the SAME lifecycle entry.
:func:`supported_hypotheses` and :func:`lifecycle_counts` read the verdict
back out for, respectively, ``goal_review``'s evidence input and the
scorecard control-plane snapshot; :func:`has_in_flight_experiment` is the
read side of the "at most one active hypothesis experiment" rule
``demand._hypothesis_items`` enforces. See ``hypothesis_verdict``'s module
docstring for the full trust argument (verdict is steering, never a
verification gate).
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

TOP_N = 5
MAX_SECTION_CHARS = 1200
DURABLE_MAX_ENTRIES = 20
STALE_AFTER_DAYS = 14
STALE_AFTER_UNTOUCHED_CYCLES = 50
# #878: how many "supported" hypotheses (newest verdict first) goal_review
# gets to cite as evidence per review — kept small like every other bounded
# evidence source that module reads (decay, goal-gaps).
SUPPORTED_TOP_N = 3
# #878 opus-review Y1 fix: a 'proposed' cycle with no terminal 'outcome' row
# is normally "still running" — but a cycle that crashed/was killed on the
# host (power loss, OOM-kill) never writes a terminal outcome at all, so
# without a timeout has_in_flight_experiment would read as permanently
# in-flight and freeze the whole hypothesis demand lane until the candidate
# ages into STALE_AFTER_DAYS (14 days). A proposed row older than this many
# days is treated as abandoned/dead rather than still-running, giving the
# lane a release path far short of the stale window.
IN_FLIGHT_TIMEOUT_DAYS = 3

_PROBLEM_PATTERNS: list[tuple[str, tuple[frozenset[str], ...]]] = [
    (
        "host_metrics_telemetry_gap",
        (
            frozenset({"host", "metrics"}),
            frozenset({"stale", "feed"}),
            frozenset({"a820ca0c8bb3"}),
        ),
    ),
    (
        "unconfirmed_script_execution",
        (
            frozenset({"script", "confirmed"}),
            frozenset({"script", "confirmation"}),
            frozenset({"script", "unconfirmed"}),
            frozenset({"script", "pycache"}),
            frozenset({"script", "usage", "confirmation"}),
        ),
    ),
    (
        "repeated_demand_waste",
        (
            frozenset({"demand", "dedup"}),
            frozenset({"demand", "rejection"}),
            frozenset({"demand", "exhausted"}),
            frozenset({"demand", "duplicate"}),
        ),
    ),
    (
        "proposer_commit_memory_drift",
        (frozenset({"proposer", "commit", "history"}),),
    ),
    (
        "ast_refactor_plateau",
        (frozenset({"ast", "refactor"}),),
    ),
    (
        "script_task_executor_yield",
        (frozenset({"script", "partial", "outcome"}),),
    ),
    (
        "direct_edit_inspection_tradeoff",
        (frozenset({"subagent", "partial", "tool", "budget"}),),
    ),
    (
        "stdlib_cache_search_turn_burn",
        (frozenset({"stdlib", "search", "turn"}),),
    ),
]

_MECHANISM_PATTERNS: list[tuple[str, tuple[frozenset[str], ...]]] = [
    (
        "host_metrics_suppression_telemetry",
        (
            frozenset({"host", "metrics"}),
            frozenset({"telemetry", "touch"}),
            frozenset({"heartbeat"}),
        ),
    ),
    (
        "harness_script_execution",
        (
            frozenset({"script", "test", "execution"}),
            frozenset({"script", "harness"}),
            frozenset({"validator", "harness"}),
            frozenset({"script", "integration", "test"}),
            frozenset({"validation", "harness", "test"}),
            frozenset({"unconfirmed", "script", "execution"}),
        ),
    ),
    (
        "demand_pre_filter_gating",
        (
            frozenset({"demand", "selection"}),
            frozenset({"demand", "filter"}),
            frozenset({"demand", "filtering"}),
            frozenset({"demand", "cool", "down"}),
            frozenset({"candidate", "demand", "exhaustion"}),
        ),
    ),
    (
        "proposer_commit_prompt_injection",
        (
            frozenset({"proposer", "commit"}),
            frozenset({"proposer", "prompt"}),
        ),
    ),
    (
        "ast_refactor_suppression",
        (frozenset({"ast", "demand"}),),
    ),
    (
        "script_task_yield",
        (frozenset({"script", "proposal"}),),
    ),
    (
        "direct_edit_gate",
        (frozenset({"subagent", "prompt", "edit"}),),
    ),
    (
        "stdlib_cache_preseed",
        (frozenset({"subagent", "prompt", "stdlib"}),),
    ),
]


def _claim_tokens(text: str) -> set[str]:
    """Order-insensitive words used only for the bounded claim taxonomy."""
    tokens = set(re.findall(r"[a-z0-9]+", text.lower().replace("_", " ")))
    aliases = {
        "scripts": "script",
        "validators": "validator",
        "demands": "demand",
        "deduplication": "dedup",
        "rejections": "rejection",
        "commits": "commit",
        "refactors": "refactor",
        "outcomes": "outcome",
    }
    return {aliases.get(token, token) for token in tokens}


def _taxonomy_tag(text: str, taxonomy: list[tuple[str, tuple[frozenset[str], ...]]]) -> str | None:
    tokens = _claim_tokens(text)
    for tag, alternatives in taxonomy:
        if any(required <= tokens for required in alternatives):
            return tag
    return None


def hypothesis_identity_key(entry: dict[str, Any]) -> str:
    """Compute deterministic identity key from problem condition and mechanism target.

    Falls back to normalized title if problem/mechanism cannot be extracted or
    if hypothesis and action fields are empty.
    """
    hypothesis = str(entry.get("hypothesis") or "").strip()
    action = str(entry.get("action") or "").strip()
    title = str(entry.get("title") or entry.get("task_title") or "").strip()

    if not hypothesis or not action:
        return f"title-{_slug(title)}" if title else ""

    problem_tag = _taxonomy_tag(hypothesis, _PROBLEM_PATTERNS)
    mechanism_tag = _taxonomy_tag(action, _MECHANISM_PATTERNS)

    if not problem_tag or not mechanism_tag:
        # If the structured pair does not identify both parts of the claim,
        # preserve the pre-#1345 title identity instead of guessing.
        return f"title-{_slug(title)}" if title else ""
    claim_str = f"{problem_tag}:{mechanism_tag}"

    h = hashlib.sha256(claim_str.encode("utf-8")).hexdigest()[:16]
    return f"claim-{h}"


_HYPOTHESIS_SERVES_RE = re.compile(r"^(?:hypothesis|demand)\s+(.+)$", re.IGNORECASE)


def _read_json(path: Path, default: Any) -> Any:
    try:
        if not path.is_file():
            return default
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def _write_json(path: Path, data: Any) -> None:
    """Atomic: temp file in the same directory, then ``os.replace``. #1346 —
    an interrupted plain ``write_text`` truncated the sidecar, the next pass
    fail-opened it to ``{}`` and the rows the change promises never to delete
    were gone."""
    tmp_name: str | None = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", delete=False
        ) as fh:
            tmp_name = fh.name
            fh.write(json.dumps(data, indent=2, ensure_ascii=False))
        os.replace(tmp_name, path)
        tmp_name = None
    except Exception:
        pass
    finally:
        if tmp_name:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass


def _ledger_window(state_dir: Path, *, days: int = IN_FLIGHT_TIMEOUT_DAYS):
    """The last ``days`` of ledger rows across the live file and its rotated
    archives (``state_access.ledger_window``, #1175). A ``proposed`` row older
    than :data:`IN_FLIGHT_TIMEOUT_DAYS` is abandoned by definition, so this
    window is the whole horizon the in-flight rule can care about."""
    from nanobot.runtime.state_access import ledger_window

    since = datetime.now(timezone.utc) - timedelta(days=days)
    return ledger_window(Path(state_dir), since_ts=since.isoformat().replace("+00:00", "Z"))


def _load_ledger_rows(state_dir: Path) -> list[dict[str, Any]]:
    return list(_ledger_window(state_dir).rows)


def _parse_ts(value: Any) -> datetime | None:
    if not value or not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except Exception:
        return None


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")[:60]


def _candidate_key(entry: dict[str, Any]) -> str:
    """Lifecycle key: ``hypothesis_id`` when present, else ``slug-<title>``.

    #1346: the id is preferred whenever it exists; the slug is the fallback
    whose use is counted (``slug_keyed``) because a restated title mints a
    fresh key. The #1345 claim key is recorded alongside (``claim``), not
    used as the key — see :func:`_candidate_claim`.
    """
    hid = str(entry.get("hypothesis_id") or "").strip()
    if hid:
        return hid
    title = str(entry.get("task_title") or entry.get("title") or "").strip()
    return f"slug-{_slug(title)}" if title else ""


def _candidate_claim(entry: dict[str, Any]) -> str:
    """#1345 claim key (``claim-<hash>``) when the entry's hypothesis/action
    resolve to a problem:mechanism pair, else ``""``.

    Recorded on the lifecycle row, NOT used as its key: (1) it collapses
    every hypothesis sharing a problem:mechanism pair into one row, so one
    ``answered`` would answer them all — right for novelty, wrong for a
    per-hypothesis verdict; (2) the ledger's ``serves: hypothesis <ref>``
    rows and ``hypothesis_ref`` name ids/titles, never claims, so keying by
    claim would break answered-detection for every existing row; (3) it
    falls back to ``title-<slug>`` for entries without hypothesis/action —
    the same rename fragility. Rows sharing a claim are counted
    (``claim_collisions``) as the direct measure of restatement.
    """
    try:
        key = hypothesis_identity_key(entry)
    except Exception:
        return ""
    return key if key.startswith("claim-") else ""


def _source_status(state_dir: Path, name: str) -> tuple[str, list[dict[str, Any]]]:
    """``("ok", entries)`` for a readable source file whose ``entries`` is a
    list (possibly empty), ``("missing", [])`` when there is no file (no
    hypotheses yet — the pre-#1346 no-op), ``("unavailable", [])`` when the
    file exists but is unparseable or wrongly shaped. #1346: absence of a
    key from the inputs can only be asserted when every input was actually
    readable — a source that cannot be read is not evidence that its
    hypotheses are gone.
    """
    path = Path(state_dir) / "hypotheses" / name
    try:
        if not path.is_file():
            return "missing", []
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return "unavailable", []
    entries = data.get("entries") if isinstance(data, dict) else None
    if not isinstance(entries, list):
        return "unavailable", []
    return "ok", [e for e in entries if isinstance(e, dict)]


_INPUT_SOURCES = ("durable.json",)  # #1356: backlog.json retired


def _input_status(state_dir: Path) -> dict[str, str]:
    return {name: _source_status(state_dir, name)[0] for name in _INPUT_SOURCES}


def _durable_candidates(state_dir: Path) -> list[dict[str, str]]:
    data = _read_json(Path(state_dir) / "hypotheses" / "durable.json", None)
    entries = data.get("entries") if isinstance(data, dict) else []
    out = []
    for entry in entries if isinstance(entries, list) else []:
        if isinstance(entry, dict):
            key = _candidate_key(entry)
            title = str(entry.get("task_title") or entry.get("title") or "").strip()
            if key and title:
                out.append({"key": key, "title": title, "source": "durable", "claim": _candidate_claim(entry)})
    return out


def _candidates_from(entries: list[dict[str, Any]], source: str) -> list[dict[str, str]]:
    """Candidate rows (key/title/source/claim) from already-read entries."""
    out: list[dict[str, str]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        key = _candidate_key(entry)
        title = str(entry.get("task_title") or entry.get("title") or "").strip()
        if key and title:
            out.append({"key": key, "title": title, "source": source, "claim": _candidate_claim(entry)})
    return out


def _dedupe_candidates(cands: list[dict[str, str]]) -> list[dict[str, str]]:
    seen: set[str] = set()
    out: list[dict[str, str]] = []
    for cand in cands:
        if cand["key"] in seen:
            continue
        seen.add(cand["key"])
        out.append(cand)
    return out


def _all_candidates(state_dir: Path) -> list[dict[str, str]]:
    return _dedupe_candidates(_durable_candidates(state_dir))


def _read_inputs(state_dir: Path) -> tuple[dict[str, str], list[dict[str, str]], set[str], int]:
    """ONE read per source (#1346 review): ``(status by file, candidates,
    present keys, id collisions)``.

    ``present`` is every key the inputs carry, including entries without a
    title (they are *in* the input, so their row is not orphaned even though
    they are not offered as candidates). Collisions are counted within a
    source.
    """
    statuses: dict[str, str] = {}
    raw: list[dict[str, str]] = []
    present: set[str] = set()
    collisions = 0
    for name in _INPUT_SOURCES:
        status, entries = _source_status(state_dir, name)
        statuses[name] = status
        if status != "ok":
            continue
        keys = [k for k in (_candidate_key(e) for e in entries) if k]
        collisions += len(keys) - len(set(keys))
        present.update(keys)
        raw.extend(_candidates_from(entries, name[: -len(".json")]))
    return statuses, _dedupe_candidates(raw), present, collisions


def _load_lifecycle_status(state_dir: Path) -> tuple[dict[str, Any], str]:
    """``(data, status)`` — ``"ok"``, ``"missing"`` (no file yet: a fresh
    sidecar is legitimate), or ``"corrupt"`` (file present but unreadable or
    mis-shaped: a fresh sidecar would overwrite rows we could not read).
    """
    path = Path(state_dir) / "hypotheses" / "lifecycle.json"
    fresh = {"schema_version": "hypothesis-lifecycle-v1", "entries": {}}
    try:
        if not path.is_file():
            return fresh, "missing"
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return fresh, "corrupt"
    if not isinstance(data, dict) or not isinstance(data.get("entries"), dict):
        return fresh, "corrupt"
    return data, "ok"


def _load_lifecycle(state_dir: Path) -> dict[str, Any]:
    return _load_lifecycle_status(state_dir)[0]


def _save_lifecycle(state_dir: Path, data: dict[str, Any]) -> None:
    _write_json(Path(state_dir) / "hypotheses" / "lifecycle.json", data)


def _serves_hypothesis_ref(serves: str) -> str | None:
    match = _HYPOTHESIS_SERVES_RE.match((serves or "").strip())
    if not match:
        return None
    return match.group(1).strip()


def _apply_verdict(state_dir: Path, entry: dict[str, Any], key: str, cycle_id: str, now_iso: str) -> None:
    """#878: compute + persist the harness-measured verdict on a hypothesis
    entry the instant it is first marked ``answered`` (same reconciliation
    pass, no separate hook). Additive to ``entry`` in place: ``verdict``,
    ``verdict_evidence``, ``verdict_at``. Also appends one
    ``{"phase": "hypothesis", "reason": "verdict", ...}`` ledger row.
    Best-effort — a verdict failure must never break ``reconcile``'s
    existing answered/stale bookkeeping."""
    verdict = None
    evidence: dict[str, Any] = {}
    try:
        from nanobot.runtime.hypothesis_verdict import classify_hypothesis_verdict

        verdict, evidence = classify_hypothesis_verdict(state_dir, cycle_id, entry.get("title") or "")
        entry["verdict"] = verdict
        entry["verdict_evidence"] = evidence
        entry["verdict_at"] = now_iso
    except Exception:
        return
    try:
        from nanobot.runtime.cycle_ledger import append_event

        append_event(
            state_dir,
            {
                "phase": "hypothesis",
                "reason": "verdict",
                "hypothesis_ref": key,
                "verdict": verdict,
                "cycle_id": str(cycle_id),
                "evidence": evidence,
            },
        )
    except Exception:
        pass


def _maybe_upgrade_inconclusive_verdict(
    state_dir: Path, entry: dict[str, Any], key: str, now_iso: str
) -> None:
    """#878 opus-review N1 fix: re-evaluate an already-answered hypothesis's
    verdict on a LATER reconcile pass if it is still ``"inconclusive"`` —
    and, per #894, also if it has NO verdict at all (``None``), which is
    the shape of any ``answered`` entry that predates #878 entirely and so
    never got a first classify pass.

    ``_apply_verdict`` originally only ran once, at the exact moment a
    candidate flips to ``answered`` — day 0. At that instant the
    confirmed-usage source (:func:`hypothesis_verdict._confirmed_usage_verdict`)
    is structurally ALWAYS either absent (no completed entry yet) or still
    inside its confirm window, so without this re-check the "supported once
    later confirmed" and "refuted once the window elapses unconfirmed"
    confirmed-usage branches could never fire in production — only
    microbench ever produced a real (non-inconclusive) verdict. This makes
    them reachable: any reconcile pass over an ``answered`` entry whose
    stored ``verdict`` is still ``"inconclusive"`` re-runs
    :func:`hypothesis_verdict.classify_hypothesis_verdict` against the SAME
    serving ``cycle_id`` (``answered_evidence``); if a measured source now
    resolves to ``supported``/``refuted``, the entry and a
    ``{"phase": "hypothesis", "reason": "verdict"}`` ledger event are
    updated exactly like the original transition. If it is STILL
    inconclusive, nothing is written and no event is appended — a
    steady-state inconclusive entry costs one classify call per reconcile
    pass, not a growing write/event history. Best-effort — a failure here
    must never break the rest of reconciliation."""
    cycle_id = entry.get("answered_evidence")
    if not cycle_id:
        return
    try:
        from nanobot.runtime.hypothesis_verdict import classify_hypothesis_verdict

        verdict, evidence = classify_hypothesis_verdict(state_dir, cycle_id, entry.get("title") or "")
    except Exception:
        return
    if verdict == "inconclusive":
        return  # unchanged — no write, no event
    entry["verdict"] = verdict
    entry["verdict_evidence"] = evidence
    entry["verdict_at"] = now_iso
    try:
        from nanobot.runtime.cycle_ledger import append_event

        append_event(
            state_dir,
            {
                "phase": "hypothesis",
                "reason": "verdict",
                "hypothesis_ref": key,
                "verdict": verdict,
                "cycle_id": str(cycle_id),
                "evidence": evidence,
            },
        )
    except Exception:
        pass


def _ref_matches_candidate(ref: str, cand: dict[str, str]) -> bool:
    ref_low = ref.lower().strip()
    if not ref_low:
        return False
    key_low = cand["key"].lower()
    title_low = cand["title"].lower()
    return ref_low == key_low or ref_low in key_low or ref_low in title_low


def reconcile(state_dir: Path, *, now: datetime | None = None) -> None:
    """Lazy lifecycle reconciliation (#751 design choice — no invasive hook
    into where cycle outcomes are recorded; this runs instead as a side
    effect of every :func:`top_candidates`/:func:`context_section` call, i.e.
    once per proposer cycle via ``llm_proposer.build_context``).

    Marks a candidate ``answered`` (with the resolving ``cycle_id`` as
    evidence) the first time a ledger ``'proposed'`` row whose ``serves``
    names it (``hypothesis <ref>``) is later followed by a same-``cycle_id``
    ``'outcome'`` row with ``outcome == "success"``. Demotes any still-
    ``active`` candidate to ``stale`` once it has gone unreferenced by any
    ``serves: hypothesis ...`` proposal for :data:`STALE_AFTER_UNTOUCHED_CYCLES`
    reconciliation passes, or :data:`STALE_AFTER_DAYS` days have elapsed
    since it was first observed — whichever comes first. Fail-open: never
    raises; a partial/corrupt read degrades to "no reconciliation this
    pass" rather than crashing the caller.

    #878: the SAME pass that first flips a candidate to ``answered`` also
    computes its harness-measured verdict (:func:`_apply_verdict`); every
    LATER pass over an ``answered`` candidate whose verdict is still
    ``"inconclusive"`` re-checks it (:func:`_maybe_upgrade_inconclusive_verdict`)
    so a confirmed-usage signal that only arrives after day 0 can still
    resolve the verdict.
    """
    try:
        state_dir = Path(state_dir)
        now = now or datetime.now(timezone.utc)
        # One read per source: candidates, the status that says whether the
        # read succeeded, and the present-key set all come from the SAME
        # bytes — a transient read failure can no longer show up as "the file
        # was fine (status ok) but held nothing (no candidates)" and orphan
        # every present row. input_id_collisions: the strategist has reused
        # ids (live durable.json 2026-09-05: hyp-0021 carried 4 different
        # hypotheses, hyp-0022 three), so an id-keyed row can silently stand
        # for several entries.
        inputs, candidates, present, input_id_collisions = _read_inputs(state_dir)
        inputs_ok = all(status == "ok" for status in inputs.values())
        if all(status == "missing" for status in inputs.values()):
            return  # no hypothesis source at all: today's behaviour, no pass recorded

        lifecycle, lifecycle_status = _load_lifecycle_status(state_dir)
        if lifecycle_status == "corrupt":
            return  # never overwrite a sidecar we could not read (#1346 review)
        entries: dict[str, Any] = lifecycle.setdefault("entries", {})
        if not any(status == "ok" for status in inputs.values()):
            # The source exists but could not be read: nothing is evaluated,
            # nothing is orphaned, and the pass is recorded so the surface
            # shows inputs_unavailable instead of a silent no-op.
            lifecycle["updated_at"] = now.isoformat().replace("+00:00", "Z")
            lifecycle["last_pass"] = {
                "at": lifecycle["updated_at"],
                "inputs": inputs,
                "inputs_ok": False,
                "evaluated": 0,
                "orphaned_now": 0,
                "slug_keyed_candidates": 0,
                "input_id_collisions": 0,
            }
            _save_lifecycle(state_dir, lifecycle)
            return

        rows = _load_ledger_rows(state_dir)
        proposed_by_cycle: dict[str, dict[str, Any]] = {}
        outcome_by_cycle: dict[str, dict[str, Any]] = {}
        for row in rows:
            cid = row.get("cycle_id")
            if not cid:
                continue
            phase = row.get("phase")
            if phase == "proposed":
                proposed_by_cycle[cid] = row
            elif phase == "outcome":
                outcome_by_cycle[cid] = row

        touched_keys: set[str] = set()
        answered_keys: dict[str, str] = {}
        for cid, prow in proposed_by_cycle.items():
            ref = _serves_hypothesis_ref(str(prow.get("serves") or ""))
            explicit_ref = str(prow.get("hypothesis_ref") or "").strip()
            if not ref and not explicit_ref:
                continue
            for cand in candidates:
                if explicit_ref:
                    matches = explicit_ref == cand["key"]
                else:
                    matches = _ref_matches_candidate(ref, cand)
                if not matches:
                    continue
                touched_keys.add(cand["key"])
                outcome_row = outcome_by_cycle.get(cid)
                if outcome_row and outcome_row.get("outcome") == "success":
                    answered_keys[cand["key"]] = str(cid)

        now_iso = now.isoformat().replace("+00:00", "Z")
        for cand in candidates:
            key = cand["key"]
            entry = entries.get(key)
            if not isinstance(entry, dict):
                entry = {}
            entry.setdefault("status", "active")
            entry.setdefault("first_seen", now_iso)
            entry.setdefault("cycles_untouched", 0)
            entry.setdefault("title", cand["title"])
            # #1346: this key was in the inputs for this pass
            entry["last_evaluated"] = now_iso
            if entry.get("orphaned"):
                entry["reappeared_at"] = now_iso
            entry.pop("orphaned", None)
            entry.pop("orphaned_at", None)
            if cand.get("claim"):
                entry["claim_key"] = cand["claim"]

            if key in answered_keys and entry.get("status") != "answered":
                entry["status"] = "answered"
                entry["answered_evidence"] = answered_keys[key]
                entry["answered_at"] = now_iso
                # #878: compute + persist the harness-measured verdict the
                # SAME pass a hypothesis is first marked answered — no
                # separate hook into where cycle outcomes are recorded,
                # consistent with this module's existing lazy-reconciliation
                # design note above.
                _apply_verdict(state_dir, entry, key, answered_keys[key], now_iso)
            elif entry.get("status") == "answered" and entry.get("verdict") in (None, "inconclusive"):
                # #878 opus-review N1 fix: re-check on every LATER pass too —
                # see _maybe_upgrade_inconclusive_verdict's docstring for why
                # the confirmed-usage source needs this to ever fire.
                # #894: also catches legacy "answered" entries that predate
                # #878 entirely and so have NO verdict field at all (verdict
                # is None, not the string "inconclusive") — those never got
                # a first classify pass and would otherwise sit unevaluated
                # forever.
                _maybe_upgrade_inconclusive_verdict(state_dir, entry, key, now_iso)

            if entry.get("status") == "active":
                if key in touched_keys:
                    entry["cycles_untouched"] = 0
                    entry["last_touched"] = now_iso
                else:
                    entry["cycles_untouched"] = int(entry.get("cycles_untouched") or 0) + 1

                first_seen = _parse_ts(entry.get("first_seen")) or now
                age_days = (now - first_seen).total_seconds() / 86400.0
                if (
                    age_days >= STALE_AFTER_DAYS
                    or entry["cycles_untouched"] >= STALE_AFTER_UNTOUCHED_CYCLES
                ):
                    entry["status"] = "stale"
                    entry["stale_at"] = now_iso

            entries[key] = entry

        # #1346: a row whose key was absent from every input this pass is
        # not evaluated again and used to read exactly like an active row.
        # Mark it (never delete it) with the last pass that did evaluate it.
        # Only when every input was readable: an unreadable source is not
        # evidence that its hypotheses are gone. ``present`` is every key the
        # inputs carry (titled or not), from the same read as ``candidates``.
        orphaned_now = 0
        if inputs_ok:
            for key, entry in entries.items():
                if key in present or not isinstance(entry, dict):
                    continue
                if not entry.get("orphaned"):
                    entry["orphaned"] = True
                    entry["orphaned_at"] = now_iso
                    if not entry.get("last_evaluated"):
                        # legacy row (pre-#1346): best-known prior evaluation
                        entry["last_evaluated"] = (
                            entry.get("last_touched") or entry.get("stale_at")
                            or entry.get("answered_at") or entry.get("first_seen") or None
                        )
                    orphaned_now += 1
        lifecycle["entries"] = entries
        lifecycle["updated_at"] = now_iso
        lifecycle["last_pass"] = {
            "at": now_iso,
            "inputs": inputs,
            "inputs_ok": inputs_ok,
            "evaluated": len(present),
            "orphaned_now": orphaned_now,
            "slug_keyed_candidates": sum(1 for k in present if k.startswith("slug-")),
            "input_id_collisions": input_id_collisions,
        }
        _save_lifecycle(state_dir, lifecycle)
    except Exception:
        pass


def top_candidates(state_dir: Path, n: int = TOP_N) -> list[dict[str, str]]:
    """Top ``n`` still-``active`` candidates, durable-order then backlog-
    order, reconciling lifecycle state first. Fail-open: returns ``[]`` on
    any error."""
    try:
        state_dir = Path(state_dir)
        reconcile(state_dir)
        candidates = _all_candidates(state_dir)
        if not candidates:
            return []
        lifecycle = _load_lifecycle(state_dir)
        entries = lifecycle.get("entries", {})
        out: list[dict[str, str]] = []
        for cand in candidates:
            status = "active"
            stored = entries.get(cand["key"])
            if isinstance(stored, dict):
                status = str(stored.get("status") or "active")
            if status != "active":
                continue
            out.append(cand)
            if len(out) >= n:
                break
        return out
    except Exception:
        return []


def context_section(state_dir: Path) -> str:
    """Bounded ``## Hypothesis backlog (candidate value sources)`` body (no
    heading — the caller adds it), one ``- [<key>] <title>`` line per
    candidate. Fail-open: returns ``""`` on any error or when there are no
    active candidates, so the caller can omit the section entirely."""
    try:
        candidates = top_candidates(state_dir, TOP_N)
        if not candidates:
            return ""
        lines = [f"- [{cand['key']}] {cand['title']}" for cand in candidates]
        section = "\n".join(lines)
        if len(section) > MAX_SECTION_CHARS:
            section = section[:MAX_SECTION_CHARS]
        return section
    except Exception:
        return ""


# ─── #878: verdict-derived readers ──────────────────────────────────────────


def supported_hypotheses(state_dir: Path, n: int = SUPPORTED_TOP_N) -> list[dict[str, Any]]:
    """Hypotheses the harness-computed verdict (:mod:`hypothesis_verdict`)
    marked ``"supported"`` — newest ``verdict_at`` first, capped to ``n``.

    Each item is ``{"title": ..., "evidence": ...}`` where ``evidence`` is
    the SAME ``verdict_evidence`` dict persisted on the lifecycle entry
    (already sourced from a measured sidecar, never instance-authored
    text). Consumed by ``goal_review._collect_evidence`` as an additional
    citable evidence line, the same way decay/goal-gap evidence already is
    — a supported hypothesis still has to pass ``goal_review``'s normal
    fail-closed ``validate_priority`` before it can ever become a priority.
    Fail-open: ``[]`` on any error or when nothing is verdict-marked yet."""
    try:
        state_dir = Path(state_dir)
        lifecycle = _load_lifecycle(state_dir)
        entries = lifecycle.get("entries", {})
        if not isinstance(entries, dict):
            return []
        ranked: list[tuple[str, dict[str, Any]]] = []
        for entry in entries.values():
            if not isinstance(entry, dict):
                continue
            if entry.get("orphaned"):
                continue  # #1346: a fossil's verdict is not current evidence
            if str(entry.get("verdict") or "") != "supported":
                continue
            title = str(entry.get("title") or "").strip()
            if not title:
                continue
            ranked.append(
                (str(entry.get("verdict_at") or ""), {"title": title, "evidence": entry.get("verdict_evidence") or {}})
            )
        ranked.sort(key=lambda pair: pair[0], reverse=True)
        return [item for _, item in ranked[:n]]
    except Exception:
        return []


def lifecycle_counts(state_dir: Path) -> dict[str, int]:
    """Counts over every lifecycle entry — read by
    ``scorecard._control_plane_snapshot`` and the dashboard for VISIBILITY
    ONLY, never fed into fitness/targets/gaps. Fail-open to ``{}``.

    #878: ``active``/``answered`` (``status``) and
    ``supported``/``refuted``/``inconclusive`` (``verdict``) are independent
    fields, so an answered entry contributes to both.

    #1346 (additive): ``total``, ``stale``, ``orphaned`` (rows whose key was
    absent from every input at the last pass — never deleted, never
    evaluated), ``evaluated_last_pass`` (rows present in the inputs at the
    last pass), ``id_keyed`` / ``slug_keyed`` (rows keyed by ``hypothesis_id``
    vs the title-slug fallback — the slug count is the direct measure of the
    rename problem), ``claim_keyed`` (rows carrying a #1345 claim key) and
    ``claim_collisions`` (rows beyond the first per claim key — restatements
    of one idea under several keys), ``inputs_unavailable`` (sources that
    could not be read at the last pass; when > 0 no orphan marks were made),
    ``last_pass_recorded`` (0 until a #1346 pass has run — then ``orphaned`` and
    ``evaluated_last_pass`` are unmeasured, not zero; a corrupt sidecar
    returns ``{}``), ``input_id_collisions`` (input entries sharing a ``hypothesis_id`` with
    another entry at the last pass — several hypotheses behind one row),
    and the key-prefix breakdown ``prefix_hypothesis`` (``hypothesis-*``, the
    ids of the planner retired in #923 — 91 of the 115 live rows on
    2026-09-05), ``prefix_hyp`` (``hyp-*``, the strategist's durable ids),
    ``prefix_slug`` (``slug-*``), ``prefix_other``.
    """
    try:
        state_dir = Path(state_dir)
        lifecycle, status = _load_lifecycle_status(state_dir)
        if status == "corrupt":
            return {}  # no data is not zero of everything
        entries = lifecycle.get("entries", {})
        if not isinstance(entries, dict):
            return {}
        counts = {
            "active": 0, "answered": 0, "supported": 0, "refuted": 0, "inconclusive": 0,
            "total": 0, "stale": 0, "orphaned": 0, "evaluated_last_pass": 0,
            "id_keyed": 0, "slug_keyed": 0, "claim_keyed": 0, "claim_collisions": 0,
            "inputs_unavailable": 0, "input_id_collisions": 0,
            "prefix_hypothesis": 0, "prefix_hyp": 0, "prefix_slug": 0, "prefix_other": 0,
            # 1 once a #1346 pass has run; 0 means orphaned/evaluated_last_pass
            # are "not yet measured", not "measured zero"
            "last_pass_recorded": 0,
        }
        last_pass = lifecycle.get("last_pass") if isinstance(lifecycle.get("last_pass"), dict) else {}
        counts["last_pass_recorded"] = 1 if last_pass.get("at") else 0
        last_at = str(last_pass.get("at") or "")
        inputs = last_pass.get("inputs") if isinstance(last_pass.get("inputs"), dict) else {}
        counts["inputs_unavailable"] = sum(1 for v in inputs.values() if v != "ok")
        counts["input_id_collisions"] = int(last_pass.get("input_id_collisions") or 0)
        claims: dict[str, int] = {}
        for key, entry in entries.items():
            if not isinstance(entry, dict):
                continue
            counts["total"] += 1
            status = str(entry.get("status") or "")
            if status in ("active", "answered", "stale"):
                counts[status] += 1
            verdict = str(entry.get("verdict") or "")
            if verdict in ("supported", "refuted", "inconclusive"):
                counts[verdict] += 1
            if entry.get("orphaned"):
                counts["orphaned"] += 1
            if last_at and str(entry.get("last_evaluated") or "") == last_at:
                counts["evaluated_last_pass"] += 1
            if str(key).startswith("slug-"):
                counts["slug_keyed"] += 1
            else:
                counts["id_keyed"] += 1
            prefix = str(key).split("-", 1)[0]
            counts["prefix_" + (prefix if prefix in ("hypothesis", "hyp", "slug") else "other")] += 1
            claim = str(entry.get("claim_key") or "")
            if claim:
                counts["claim_keyed"] += 1
                claims[claim] = claims.get(claim, 0) + 1
        counts["claim_collisions"] = sum(n - 1 for n in claims.values() if n > 1)
        return counts
    except Exception:
        return {}


def has_in_flight_experiment(
    state_dir: Path,
    *,
    now: datetime | None = None,
    ledger_rows: list[dict[str, Any]] | None = None,
) -> bool:
    """True iff some ``active``-status hypothesis candidate has a
    ``'proposed'`` ledger row (``serves: hypothesis <ref>``) whose
    ``cycle_id`` has NOT YET produced a terminal ``'outcome'`` row AND whose
    ``proposed`` row is younger than :data:`IN_FLIGHT_TIMEOUT_DAYS` — i.e.
    an experiment cycle for it is currently running or awaiting its
    verdict.

    Used by ``demand._hypothesis_items`` to enforce the #878 "at most one
    active hypothesis experiment" rule: while this is true, no NEW
    hypothesis-kind demand item is minted this cycle (the loop keeps
    presenting whatever else it has instead of stacking a second parallel
    experiment on top of the one already running). Deliberately does not
    consult ``exhausted``/``completed`` state — this is only about a cycle
    that is currently open, not about retry bookkeeping.

    #878 opus-review Y1 fix: a serving cycle that crashed on the host
    (power loss, OOM-kill, process kill) never writes a terminal
    ``'outcome'`` row at all — without a timeout this would read as
    permanently in-flight, freezing the whole hypothesis demand lane until
    the candidate separately ages into :data:`STALE_AFTER_DAYS` (14 days).
    A ``'proposed'`` row older than :data:`IN_FLIGHT_TIMEOUT_DAYS` is
    therefore treated as abandoned, not still-running, regardless of
    whether it ever gets an outcome — a row with a missing/unparseable
    ``ts`` is conservatively still counted as in-flight (cannot confirm
    it's timed out). Fail-open: ``False`` on any error (never blocks demand
    collection); ``True`` on a ``partial``/``unavailable`` ledger window
    (#1175: a rotated-out serving row must not mint a second experiment)."""
    try:
        state_dir = Path(state_dir)
        now = now or datetime.now(timezone.utc)
        candidates = _all_candidates(state_dir)
        if not candidates:
            return False
        lifecycle = _load_lifecycle(state_dir)
        entries = lifecycle.get("entries", {})
        active_keys = {
            cand["key"]
            for cand in candidates
            if str((entries.get(cand["key"]) or {}).get("status") or "active") == "active"
        }
        if not active_keys:
            return False

        if ledger_rows is not None:
            rows = ledger_rows
            # demand.LedgerRows carries the window's evidence status; a plain
            # list (older callers, test doubles) reads as complete.
            ledger_status = str(getattr(ledger_rows, "status", "complete") or "complete")
        else:
            from nanobot.runtime.state_access import evidence_status

            window = _ledger_window(state_dir)
            rows, ledger_status = list(window.rows), evidence_status(window)
        if ledger_status != "complete":
            # #1175: a serving row that rotated out of view, or a ledger that
            # cannot be read, must not mint a second experiment. Assume
            # in-flight; the lane reopens on the next complete read.
            return True
        outcome_cycle_ids: set[str] = set()
        proposed_cycle_ts: dict[str, datetime | None] = {}
        for row in rows:
            cid = row.get("cycle_id")
            if not cid:
                continue
            phase = row.get("phase")
            if phase == "outcome":
                outcome_cycle_ids.add(cid)
                continue
            if phase != "proposed":
                continue
            ref = _serves_hypothesis_ref(str(row.get("serves") or ""))
            if not ref:
                continue
            for cand in candidates:
                if cand["key"] in active_keys and _ref_matches_candidate(ref, cand):
                    proposed_cycle_ts[cid] = _parse_ts(row.get("ts"))
                    break

        for cid, prow_ts in proposed_cycle_ts.items():
            if cid in outcome_cycle_ids:
                continue
            if prow_ts is not None:
                age_days = (now - prow_ts).total_seconds() / 86400.0
                if age_days >= IN_FLIGHT_TIMEOUT_DAYS:
                    continue  # abandoned — no longer counts as in-flight
            return True
        return False
    except Exception:
        return False


def append_hypotheses(state_dir: Path | str, new_entries: list[dict[str, Any]]) -> int:
    """Append structured hypothesis entries to ``state_dir/hypotheses/durable.json`` (#999).

    This is the writer of ``durable.json`` — the strategist's daily run
    (``strategist.run_strategist``) calls it, which is why the file's mtime
    moves once a day at 00:00 UTC. The docstring used to say ``backlog.json``
    (the bridge's per-cycle snapshot, a different file) and #1222 spent a
    row hunting for an out-of-repo writer that was this function all along.

    Preserves the existing schema (dict with schema, updated_at, entries).
    Writes atomically via tempfile + os.replace.
    Returns the number of valid entries actually appended.
    """
    state_dir = Path(state_dir)
    hypotheses_dir = state_dir / "hypotheses"
    hypotheses_dir.mkdir(parents=True, exist_ok=True)
    backlog_path = hypotheses_dir / "durable.json"

    raw_data = _read_json(backlog_path, None)
    if isinstance(raw_data, dict) and isinstance(raw_data.get("entries"), list):
        backlog_data = dict(raw_data)
        entries = list(backlog_data.get("entries") or [])
    else:
        backlog_data = {"schema": "hypothesis-durable-v1", "entries": []}
        entries = []

    # Repair duplicate FIFO-era ids before exact identity links can act on
    # them. Unique legacy ids stay unchanged; each duplicate receives the
    # same content identity used for new entries. Lifecycle rows under the old
    # id remain historical rather than being guessed onto one duplicate.
    id_counts: dict[str, int] = {}
    for entry in entries:
        if isinstance(entry, dict):
            hypothesis_id = str(entry.get("hypothesis_id") or "").strip()
            if hypothesis_id:
                id_counts[hypothesis_id] = id_counts.get(hypothesis_id, 0) + 1
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        hypothesis_id = str(entry.get("hypothesis_id") or "").strip()
        if id_counts.get(hypothesis_id, 0) <= 1:
            continue
        title = str(entry.get("title") or entry.get("task_title") or "").strip()
        hypothesis_text = str(entry.get("hypothesis") or "").strip()
        entry["hypothesis_id"] = "hyp-" + hashlib.sha256(
            f"{title}\n{hypothesis_text}".encode("utf-8")
        ).hexdigest()[:16]

    # Map existing titles / keys to avoid duplicate additions
    # Cheap first pass: exact title dedup
    # Second pass: deterministic claim identity key
    title_to_entry: dict[str, dict[str, Any]] = {}
    claim_to_entry: dict[str, dict[str, Any]] = {}

    for e in entries:
        if not isinstance(e, dict):
            continue
        t = str(e.get("title") or e.get("task_title") or e.get("hypothesis") or "").strip().lower()
        if t and t not in title_to_entry:
            title_to_entry[t] = e
        ckey = hypothesis_identity_key(e)
        if ckey and ckey not in claim_to_entry:
            claim_to_entry[ckey] = e

    def _priority_score(p: Any) -> float:
        if isinstance(p, (int, float)):
            return float(p)
        p_str = str(p or "").strip().lower()
        mapping = {"high": 1.0, "medium": 0.5, "low": 0.2}
        return mapping.get(p_str, 0.5)

    def _strengthen_entry(target: dict[str, Any], incoming: dict[str, Any]) -> None:
        target["seen_count"] = int(target.get("seen_count") or 1) + 1
        # Raise priority if incoming has higher priority
        p_target = _priority_score(target.get("priority"))
        p_incoming = _priority_score(incoming.get("priority"))
        if p_incoming > p_target:
            target["priority"] = incoming.get("priority")

        # Append unique evidence
        incoming_evidence: list[str] = []
        raw_ev = incoming.get("evidence") or incoming.get("data_to_collect")
        if isinstance(raw_ev, list):
            incoming_evidence = [str(x).strip() for x in raw_ev if str(x).strip()]
        elif isinstance(raw_ev, str) and raw_ev.strip():
            incoming_evidence = [raw_ev.strip()]

        existing_evidence = target.get("evidence")
        if isinstance(existing_evidence, list):
            target_evidence = [str(value).strip() for value in existing_evidence if str(value).strip()]
        elif isinstance(existing_evidence, str) and existing_evidence.strip():
            target_evidence = [existing_evidence.strip()]
        else:
            target_evidence = []

        for ev in incoming_evidence:
            if ev not in target_evidence:
                target_evidence.append(ev)
        # durable-v1 evidence is a string on the live reader path. Preserve
        # that shape while retaining each distinct observation.
        target["evidence"] = "\n".join(target_evidence)

    appended = 0
    updated = False
    now_iso = datetime.now(timezone.utc).isoformat()
    for item in new_entries:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title") or item.get("task_title") or "").strip()
        hypothesis_text = str(item.get("hypothesis") or "").strip()
        if not title and not hypothesis_text:
            continue

        lookup_key = (title or hypothesis_text).lower()
        matched_target: dict[str, Any] | None = None

        if lookup_key in title_to_entry:
            matched_target = title_to_entry[lookup_key]
        else:
            item_ckey = hypothesis_identity_key(item)
            if item_ckey in claim_to_entry:
                matched_target = claim_to_entry[item_ckey]

        if matched_target is not None:
            _strengthen_entry(matched_target, item)
            updated = True
            try:
                from nanobot.runtime.cycle_ledger import append_event

                append_event(
                    state_dir,
                    {
                        "phase": "hypothesis",
                        "reason": "claim_collision",
                        "existing_hypothesis_id": str(matched_target.get("hypothesis_id") or ""),
                        "incoming_hypothesis_id": str(item.get("hypothesis_id") or ""),
                    },
                )
            except Exception:
                pass
            continue

        hypothesis_id = str(item.get("hypothesis_id") or "").strip()
        if not hypothesis_id:
            hypothesis_id = "hyp-" + hashlib.sha256(
                f"{title}\n{hypothesis_text}".encode("utf-8")
            ).hexdigest()[:16]

        entry_record: dict[str, Any] = {
            "hypothesis_id": hypothesis_id,
            "task_title": title or hypothesis_text[:80],
            "title": title or hypothesis_text[:80],
            "hypothesis": hypothesis_text,
            "action": str(item.get("action") or "").strip(),
            "data_to_collect": str(item.get("data_to_collect") or "").strip(),
            "insight_criterion": str(item.get("insight_criterion") or "").strip(),
            "evidence": "\n".join(
                str(value).strip()
                for value in (
                    item.get("evidence")
                    if isinstance(item.get("evidence"), list)
                    else [item.get("evidence") or item.get("data_to_collect")]
                )
                if str(value).strip()
            ),
            "priority": item.get("priority", "medium"),
            "seen_count": 1,
            "source": str(item.get("source") or "strategist"),
            "created_at": str(item.get("created_at") or now_iso),
        }
        entries.append(entry_record)
        if lookup_key:
            title_to_entry[lookup_key] = entry_record
        item_ckey = hypothesis_identity_key(entry_record)
        if item_ckey:
            claim_to_entry[item_ckey] = entry_record
        appended += 1

    trimmed = len(entries) > DURABLE_MAX_ENTRIES
    if trimmed:
        entries = entries[-DURABLE_MAX_ENTRIES:]
        backlog_data["entries"] = entries

    if appended > 0 or updated or trimmed or not new_entries:
        backlog_data["updated_at"] = now_iso
        backlog_data["entries"] = entries

        fd, tmp = tempfile.mkstemp(prefix=".backlog.", dir=str(hypotheses_dir))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                json.dump(backlog_data, fh, indent=2, ensure_ascii=False)
                fh.write("\n")
                fh.flush()
                os.fsync(fh.fileno())
            if os.name != "nt":
                os.chmod(tmp, 0o644)  # mkstemp creates 0600; normalize for non-agent readers (#1096)
            os.replace(tmp, backlog_path)
        finally:
            try:
                os.unlink(tmp)
            except FileNotFoundError:
                pass

    return appended
