"""#1857: ``skills/index.md`` -- the derivable, machine-generated path that
replaces the resident skills catalogue.

The catalogue cost ~4,048 resident characters every cycle and was read in
1 cycle of 24 (#1805): reachable is not read, and paying for reachability
in the prompt bought nothing. The fix is not "make it more prominent" (it
was already fully resident) -- it is to make the instruction to look
*unconditional* and the path *derivable*, the same shape ADR-028 rule 5
proved for the diary at 84% reach. This module owns the derivable half.

Never hand-maintained. The operator's own precondition check on #1857
named the risk precisely: "An index the loop must remember to update is a
second thing that can silently go stale... worse than the conditional it
replaces, because it fails silently while looking obeyed." So the loop
never writes this file -- :func:`write_skills_index_if_changed` is called
only by the bridge, after a cycle that touched ``skills/`` integrates
(``nanobot.runtime.bridge``'s post-integration step), so the index can
never be older than the skills it lists.

Content is not reinvented here: :meth:`SkillsLoader.build_skills_summary`
already renders exactly the "one line per skill" format the old resident
catalogue used (#1732) -- this module reuses it verbatim rather than a
second description-extraction path that could read a skill differently
than the catalogue once did.
"""
from __future__ import annotations

from pathlib import Path

#: #1857: the single home for which builtin skills the self-evolving loop
#: never sees -- operator-only or off-topic (weather, tmux, clawhub) or
#: loop-irrelevant (cron, summarize, github). The bridge's own executor
#: prompt (``excluded_skill_names=``) and this index must agree, or the
#: index would list a skill the loop's own prompt tells it does not exist
#: for interactive/other reasons -- see ``bridge.py``'s import of this name
#: rather than a second, independently-typed list.
LOOP_EXCLUDED_SKILLS: tuple[str, ...] = ("weather", "tmux", "clawhub", "cron", "summarize", "github")

INDEX_RELPATH = "skills/index.md"

_HEADER = (
    "# Skills index\n\n"
    "Generated by the harness (`nanobot.runtime.skills_index`) after any cycle "
    "that changes `skills/` -- never hand-edit; your edit will be overwritten "
    "the next time a skill changes. Read a skill's own `SKILL.md` (path given "
    "below each entry) for its full instructions before using it.\n\n"
)


def render_skills_index(selfevo_repo: Path) -> str:
    """The full content ``skills/index.md`` should hold, given the skills
    currently on disk under ``<selfevo_repo>/skills/``.

    A pure function over the filesystem: no state, no git, so it is safe to
    call speculatively (e.g. to check whether the file WOULD change) without
    writing anything.
    """
    from nanobot.agent.skills import SkillsLoader

    loader = SkillsLoader(Path(selfevo_repo))
    summary = loader.build_skills_summary(excluded_names=list(LOOP_EXCLUDED_SKILLS), compact=True)
    body = summary if summary else "(no skills yet)"
    return _HEADER + body + "\n"


def write_skills_index_if_changed(selfevo_repo: Path) -> bool:
    """Write ``skills/index.md`` if its content differs from what
    :func:`render_skills_index` would produce now. Returns whether the file
    changed (created or content differed) -- callers that need to ``git
    add``/commit only do so when this is True, so a cycle that did not
    actually change any skill produces no bookkeeping-only diff.

    Fail-open: an unreadable skills directory or a write error must never
    raise into the caller -- returns False (nothing written) rather than
    interrupting the cycle it is running inside.
    """
    try:
        target = Path(selfevo_repo) / INDEX_RELPATH
        new_content = render_skills_index(selfevo_repo)
        existing = target.read_text(encoding="utf-8") if target.is_file() else None
        if existing == new_content:
            return False
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(new_content, encoding="utf-8")
        return True
    except Exception:
        return False
