"""Self-maintained SYSTEM_MAP for the self-evolving instance repo (#749).

Confirmed failure this fixes: the loop shipped ``monitor_memory.py`` hours
after ``track_memory.py`` (a near-duplicate script under a different name)
because nothing in the proposer's context shows what already exists — only
~2.5 hours of ledger/goal-text memory (#707's ``llm_proposer.build_context``).
openwiki-inspired fix: the instance repo carries a deterministic,
non-LLM-generated ``docs/SYSTEM_MAP.md`` (script inventory + near-duplicate
name-token groups), regenerated by the loop itself and fed back into the
proposer's context (see ``nanobot.runtime.llm_proposer.build_context``).

Everything here is deterministic (NO LLM call) and fail-open: any error
degrades to "skip this update" / "empty section", never raises into the
calling cycle. Two entry points:

- :func:`generate_system_map` — pure function, no I/O side effects beyond
  reading ``selfevo_repo`` (scripts + any pre-existing ``docs/SYSTEM_MAP.md``
  to carry over its hand-edited ``## Backlog``/``## Completed`` sections).
- :func:`update_system_map` — the watermark + no-op gate (openwiki pattern):
  writes ``docs/SYSTEM_MAP.md`` in ``selfevo_repo`` only when the instance
  repo's git HEAD has moved since the last update AND the regenerated
  content actually differs (content-hash gate) from what's already on disk.
  Does NOT git-commit — the loop's own cycle commits changes; this module is
  a pure file-write.
"""
from __future__ import annotations

import ast
import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

_SCRIPT_DIRS = ("scripts", "surfaces")
_TRIVIAL_TOKENS = frozenset()  # deliberately empty — see module docstring / proposal.md alternatives
_MIN_TOKEN_LEN = 4
_JACCARD_THRESHOLD = 0.5

_HEADER = "# SYSTEM MAP"
_GENERATED_NOTE = (
    "_generated by the runtime — do not hand-edit sections below; the "
    "hand-curated Backlog and Completed sections are preserved verbatim "
    "across regeneration._"
)
_INVENTORY_HEADING = "## Inventory"
_DUPES_HEADING = "## Near-duplicate candidates"
_BACKLOG_HEADING = "## Backlog"
_COMPLETED_HEADING = "## Completed"

_HEADING_RE = re.compile(r"^## .+$", re.MULTILINE)


def _iter_script_files(selfevo_repo: Path) -> list[Path]:
    selfevo_repo = Path(selfevo_repo)
    files: list[Path] = []
    for dirname in _SCRIPT_DIRS:
        d = selfevo_repo / dirname
        if not d.is_dir():
            continue
        for path in d.glob("*.py"):
            if path.is_file():
                files.append(path)
    return files


def _first_docstring_line(path: Path) -> str:
    """Best-effort one-line description: AST module docstring, else the
    first ``#`` comment line, else a fixed placeholder. Never raises."""
    try:
        source = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return "(no description)"

    try:
        tree = ast.parse(source)
        doc = ast.get_docstring(tree)
        if doc:
            first_line = doc.strip().splitlines()[0].strip()
            if first_line:
                return first_line
    except Exception:
        pass

    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("#!"):
            continue
        if stripped.startswith("#"):
            comment = stripped.lstrip("#").strip()
            if comment:
                return comment
        elif stripped:
            # First non-comment, non-blank line with no docstring/comment
            # found yet — stop looking, this file has no header comment.
            break

    return "(no description)"


def _rel_label(selfevo_repo: Path, path: Path) -> str:
    try:
        return path.relative_to(Path(selfevo_repo)).as_posix()
    except Exception:
        return path.name


def inventory_entries(selfevo_repo: Path) -> list[tuple[str, str, float]]:
    """Return ``(rel_path, description, mtime)`` tuples, sorted by
    ``rel_path``. Fail-open: returns ``[]`` on any error."""
    try:
        selfevo_repo = Path(selfevo_repo)
        entries: list[tuple[str, str, float]] = []
        for path in _iter_script_files(selfevo_repo):
            rel = _rel_label(selfevo_repo, path)
            desc = _first_docstring_line(path)
            try:
                mtime = path.stat().st_mtime
            except Exception:
                mtime = 0.0
            entries.append((rel, desc, mtime))
        entries.sort(key=lambda e: e[0])
        return entries
    except Exception:
        return []


def inventory_lines(selfevo_repo: Path) -> list[str]:
    """``- <rel_path> — <description>`` lines, sorted by path. Fail-open."""
    try:
        return [f"- {rel} — {desc}" for rel, desc, _mtime in inventory_entries(selfevo_repo)]
    except Exception:
        return []


def _name_tokens(rel_path: str) -> set[str]:
    base = Path(rel_path).stem
    tokens = {tok for tok in base.split("_") if len(tok) >= _MIN_TOKEN_LEN}
    return tokens - _TRIVIAL_TOKENS


def _overlap_coefficient(a: set[str], b: set[str]) -> float:
    """Szymkiewicz–Simpson overlap coefficient: intersection size over the
    SMALLER set's size, not the union (plain Jaccard). Two 2-token names
    sharing one token (e.g. ``track_memory``/``monitor_memory``, sharing
    ``memory``) is exactly the confirmed near-duplicate case this module
    exists to catch — plain Jaccard (1/3 for that pair) would miss it,
    while the overlap coefficient (1/2) catches it at the 0.5 threshold."""
    if not a or not b:
        return 0.0
    inter = len(a & b)
    smaller = min(len(a), len(b))
    return inter / smaller if smaller else 0.0


def near_duplicate_groups(rel_paths: list[str]) -> list[list[str]]:
    """Group ``rel_paths`` whose basename token sets overlap heavily
    (overlap coefficient >= 0.5 over 4+-char tokens). Deterministic
    union-find; only groups of >= 2 are returned, each sorted, groups sorted
    by their first member. Fail-open: returns ``[]`` on any error."""
    try:
        names = sorted(rel_paths)
        tokens = {name: _name_tokens(name) for name in names}
        parent = {name: name for name in names}

        def find(x: str) -> str:
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        def union(x: str, y: str) -> None:
            rx, ry = find(x), find(y)
            if rx != ry:
                parent[ry] = rx

        for i, a in enumerate(names):
            for b in names[i + 1 :]:
                if _overlap_coefficient(tokens[a], tokens[b]) >= _JACCARD_THRESHOLD:
                    union(a, b)

        groups: dict[str, list[str]] = {}
        for name in names:
            groups.setdefault(find(name), []).append(name)

        result = [sorted(members) for members in groups.values() if len(members) >= 2]
        result.sort(key=lambda members: members[0])
        return result
    except Exception:
        return []


def _extract_section(markdown: str, heading: str) -> str | None:
    """Return the verbatim text of the section starting at ``heading``
    (inclusive) up to (excluding) the next ``## `` heading or EOF, or
    ``None`` if ``heading`` is not present as an actual heading line (a
    mention of the same words inside prose elsewhere in the file does not
    count — only a line matching ``^## <heading text>$`` anchors a section)."""
    heading_re = re.compile(rf"^{re.escape(heading)}\s*$", re.MULTILINE)
    start_match = heading_re.search(markdown)
    if start_match is None:
        return None
    rest = markdown[start_match.start():]
    # Find the next heading after this section's own heading line.
    next_match = _HEADING_RE.search(rest, len(start_match.group(0)))
    end = next_match.start() if next_match else len(rest)
    return rest[:end].rstrip("\n")


def parse_inventory_section(markdown: str) -> list[str]:
    """Extract ``- ...`` bullet lines from the ``## Inventory`` section of a
    previously-generated SYSTEM_MAP.md. Fail-open: returns ``[]`` on any
    error or if the section is absent."""
    try:
        section = _extract_section(markdown, _INVENTORY_HEADING)
        if not section:
            return []
        lines = []
        for line in section.splitlines():
            if line.startswith("- "):
                lines.append(line)
        return lines
    except Exception:
        return []


def generate_system_map(selfevo_repo: Path) -> str:
    """Deterministic (NO LLM) SYSTEM_MAP.md content for ``selfevo_repo``.

    Carries over the previous ``## Backlog`` / ``## Completed`` sections
    verbatim (if a prior ``docs/SYSTEM_MAP.md`` exists) so the machinery
    never destroys operator/loop-curated content. Fail-open: any error
    returns a minimal valid map rather than raising.
    """
    try:
        selfevo_repo = Path(selfevo_repo)
        entries = inventory_entries(selfevo_repo)
        rel_paths = [rel for rel, _desc, _mtime in entries]

        parts = [_HEADER, "", _GENERATED_NOTE, "", _INVENTORY_HEADING, ""]
        if entries:
            parts.extend(f"- {rel} — {desc}" for rel, desc, _mtime in entries)
        else:
            parts.append("(no scripts found)")
        parts.append("")

        parts.append(_DUPES_HEADING)
        parts.append("")
        groups = near_duplicate_groups(rel_paths)
        if groups:
            for group in groups:
                parts.append(f"- {', '.join(group)}")
        else:
            parts.append("(none detected)")
        parts.append("")

        existing_path = selfevo_repo / "docs" / "SYSTEM_MAP.md"
        if existing_path.is_file():
            try:
                existing_text = existing_path.read_text(encoding="utf-8")
            except Exception:
                existing_text = ""
            for heading in (_BACKLOG_HEADING, _COMPLETED_HEADING):
                carried = _extract_section(existing_text, heading)
                if carried:
                    parts.append(carried)
                    parts.append("")

        return "\n".join(parts).rstrip("\n") + "\n"
    except Exception:
        return f"{_HEADER}\n\n{_GENERATED_NOTE}\n\n{_INVENTORY_HEADING}\n\n(no scripts found)\n"


def _git_head(selfevo_repo: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(selfevo_repo), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            return None
        head = result.stdout.strip()
        return head or None
    except Exception:
        return None


def _watermark_path(state_dir: Path) -> Path:
    return Path(state_dir) / "system_map" / "watermark.json"


def _load_watermark(state_dir: Path) -> dict | None:
    path = _watermark_path(state_dir)
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def update_system_map(selfevo_repo: Path, state_dir: Path) -> bool:
    """Watermark + content-hash no-op gate (openwiki pattern).

    Returns ``True`` iff ``selfevo_repo/docs/SYSTEM_MAP.md`` was written this
    call, ``False`` for every no-op path (including any failure — fail-open,
    never raises).

    Gate 1 (cheap, avoids all regeneration work): if a watermark exists and
    its ``git_head`` equals the instance repo's current HEAD, nothing has
    changed since the last update — return ``False`` immediately.

    Gate 2 (content hash): only after regenerating, if the new content's
    sha256 matches the watermark's stored ``content_sha256``, the file is
    NOT rewritten and the watermark is NOT updated (so a future HEAD change
    that still yields identical content keeps costing only Gate 1's cheap
    ``git rev-parse``, not a disk write).
    """
    try:
        selfevo_repo = Path(selfevo_repo)
        state_dir = Path(state_dir)
        if not selfevo_repo.is_dir():
            return False

        current_head = _git_head(selfevo_repo)
        if current_head is None:
            return False

        watermark = _load_watermark(state_dir)
        if watermark is not None and watermark.get("git_head") == current_head:
            return False

        content = generate_system_map(selfevo_repo)
        new_sha = hashlib.sha256(content.encode("utf-8")).hexdigest()

        if watermark is not None and watermark.get("content_sha256") == new_sha:
            return False

        target = selfevo_repo / "docs" / "SYSTEM_MAP.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

        wm_path = _watermark_path(state_dir)
        wm_path.parent.mkdir(parents=True, exist_ok=True)
        wm_path.write_text(
            json.dumps(
                {
                    "updated_at_utc": datetime.now(timezone.utc).isoformat(),
                    "git_head": current_head,
                    "content_sha256": new_sha,
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return True
    except Exception:
        return False
